%% Check if Question is Defined
try
    if ~exist('questionNum','var') || isempty(questionNum)
        error('The variable `questionNum` must be set, e.g. questionNum = 1 for Question 1');
    end
catch ME
    if strcmp(ME.message,'Undefined function or variable ''questionNum''.')
        error('The variable `questionNum` must exist, e.g. set questionNum = 1 for Question 1');
    else
        rethrow(ME);
    end
end
%% Set Default Graphics Settings
% https://uk.mathworks.com/help/matlab/ref/groot.html
set(groot,  'DefaultLineLineWidth', 2.5, ...
            'DefaultTextInterpreter', 'LaTeX', ...
            'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
            'DefaultAxesFontName', 'LaTeX', ...
            'DefaultLegendInterpreter', 'LaTeX', ...
            'DefaultAxesLineWidth', 1.5, ...
            'DefaultStemLineWidth', 2.5, ...
            'DefaultStemMarker', 'none', ...
            'DefaultAxesFontSize', 16, ...
            'DefaultAxesBox', 'on', ...
            'DefaultAxesColor', [1, 1, 1], ...
            'DefaultFigureColor', [1, 1, 1], ...
            'DefaultFigureInvertHardcopy', 'off', ...
            'DefaultFigurePaperUnits', 'inches', ...
            'DefaultFigureUnits', 'inches', ...
            'DefaultFigurePaperPosition', [0, 0, 5, 3], ...
            'DefaultFigurePaperSize', [6.5, 3], ...
            'DefaultFigurePosition', [0.1, 0.1, 6.4, 2.9], ...
            'DefaultLineMarkerSize', 20, ...
            'DefaultAxesFontName', 'Palatino');

        
%% Global Variables Initialisation (all capital)
COLORS = get(groot, 'factoryAxesColorOrder');

%% Define Question specific
switch questionNum
    case 1
        disp('Initialising Q1 specific variables');
        
    case 2
        disp('Initialising Q2 specific variables');
        
    case 3
        disp('Initialising Q3 specific variables');
        
    case 4
        disp('Initialising Q4 specific variables');
end
    