%% Check if Question is Defined
try
    if ~exist('questionNum','var') || isempty(questionNum)
        error('The variable `questionNum` must be set, e.g. questionNum = 1 for Question 1');
    end
catch ME
    if strcmp(ME.message,'Undefined function or variable ''questionNum''.')
        error('The variable `questionNum` must exist, e.g. set questionNum = 1 for Question 1');
    else
        rethrow(ME);
    end
end
%% Add customFunction folder to path
addpath('customFunctions')

%% Check ToolBoxes are all installed

%% Set Default Graphics Settings
% https://uk.mathworks.com/help/matlab/ref/groot.html
% https://uk.mathworks.com/help/matlab/ref/matlab.ui.root-properties.html
% listfonts     : will list available fonts
set(groot,  'DefaultLineLineWidth', 1.75, ...
            'DefaultTextInterpreter', 'LaTeX', ...
            'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
            'DefaultAxesFontName', 'LaTeX', ...
            'DefaultLegendInterpreter', 'LaTeX', ...
            'DefaultAxesLineWidth', 1, ...
            'DefaultStemLineWidth', 1.75, ...
            'DefaultAxesXGrid', 'on', ...
            'DefaultAxesYGrid', 'on', ...
            'DefaultAxesZGrid', 'on', ...
            'DefaultStemMarker', 'none', ...
            'DefaultAxesFontSize', 16, ...
            'DefaultAxesBox', 'on', ...
            'DefaultAxesColor', [1, 1, 1], ...
            'DefaultFigureColor', [1, 1, 1], ...
            'DefaultFigureInvertHardcopy', 'off', ...
            'DefaultFigurePaperUnits', 'inches', ...
            'DefaultFigureUnits', 'inches', ...
            'DefaultFigurePaperPosition', [0, 0, 5, 3], ...
            'DefaultFigurePaperSize', [6.5, 3], ...
            'DefaultFigurePosition', [0.1, 1, 6.4, 2.9], ...
            'DefaultLineMarkerSize', 18, ...
            'DefaultAxesFontName', 'Palatino');

        
%% Global Variables Initialisation (all capital)
COLORS = get(groot, 'factoryAxesColorOrder');
SAVE_FIGS = false; % Default is to not save figures
POSITION.subplot211 = [0.13 0.594109195402299 0.775 0.302765805851453];
POSITION.subplot212 = [0.13 0.179005029331679 0.775 0.303035200553379];
%% Define Question specific
switch questionNum
    case 1
        disp('Initialising Q1 specific variables');
        
    case 2
        disp('Initialising Q2 specific variables');
        
    case 3
        disp('Initialising Q3 specific variables');
        
    case 4
        disp('Initialising Q4 specific variables');
end
    