%% Check if Question is Defined
try
    if ~exist('questionNum','var') || isempty(questionNum)
        questionNum = 0;
    end
catch ME
%     error('The variable `questionNum` must exist, e.g. set questionNum = 1 for Question 1');
    questionNum = 0;
end
%% Add customFunction folder to path
addpath('customFunctions')

%% Check ToolBoxes are all installed

%% Set Default Graphics Settings
% https://uk.mathworks.com/help/matlab/ref/groot.html
% https://uk.mathworks.com/help/matlab/ref/matlab.ui.root-properties.html
% listfonts     : will list available fonts
set(groot,  'DefaultLineLineWidth', 1.75, ...
            'DefaultTextInterpreter', 'LaTeX', ...
            'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
            'DefaultAxesFontName', 'LaTeX', ...
            'DefaultLegendInterpreter', 'LaTeX', ...
            'DefaultAxesLineWidth', 1, ...
            'DefaultStemLineWidth', 1.75, ...
            'DefaultAxesXGrid', 'on', ...
            'DefaultAxesYGrid', 'on', ...
            'DefaultAxesZGrid', 'on', ...
            'DefaultStemMarker', 'none', ...
            'DefaultAxesFontSize', 16, ...
            'DefaultAxesBox', 'on', ...
            'DefaultAxesColor', [1, 1, 1], ...
            'DefaultFigureColor', [1, 1, 1], ...
            'DefaultFigureInvertHardcopy', 'off', ...
            'DefaultFigurePaperUnits', 'inches', ...
            'DefaultFigureUnits', 'inches', ...
            'DefaultFigurePaperPosition', [0, 0, 5, 3], ...
            'DefaultFigurePaperSize', [6.5, 3], ...
            'DefaultFigurePosition', [0.1, 1, 6.4, 2.9], ...
            'DefaultLineMarkerSize', 18, ...
            'DefaultAxesFontName', 'Palatino Linotype');

        
%% Global Variables Initialisation (all capital)
COLORS = get(groot, 'factoryAxesColorOrder');
SAVE_FIGS = false; % Default is to not save figures
POSITION.subplot211 = [0.13 0.594 0.775 0.303];
POSITION.subplot212 = [0.13 0.179 0.775 0.303];
%% Define Question specific
switch questionNum
    case 1
        disp('Q1: Classical and Modern Spectrum Estimation');
        
    case 2
        disp('Q2: Adaptive Signal Processing');
        
    case 3
        disp('Q3: Widely Linear Filtering and Adaptive Spectrum Estimation');
        
    case 4
        disp('Q4: From LMS to Deep Learning');
end
    